#pragma once

#include <map>

namespace konsole
{
	enum class Symbol
	{
		TEXTURE_LIGHT = 176,
		TEXTURE_MEDIUM = 177,
		TEXTURE_DARK = 178,
		FILL_ALL = 219,
		FILL_TOP = 223,
		FILL_BOTTOM = 220,
		BORDER_DOUBLE_CORNER_TL = 201,
		BORDER_DOUBLE_CORNER_TR = 187,
		BORDER_DOUBLE_CORNER_BL = 200,
		BORDER_DOUBLE_CORNER_BR = 188,
		BORDER_DOUBLE_T_LEFT = 204,
		BORDER_DOUBLE_T_RIGHT = 185,
		BORDER_DOUBLE_T_TOP = 203,
		BORDER_DOUBLE_T_BOTTOM = 202,
		BORDER_DOUBLE_HORIZONTAL = 205,
		BORDER_DOUBLE_VERTICAL = 186,
		BORDER_DOUBLE_CROSS = 206,
		BORDER_SINGLE_CORNER_TL = 218,
		BORDER_SINGLE_CORNER_TR = 191,
		BORDER_SINGLE_CORNER_BL = 192,
		BORDER_SINGLE_CORNER_BR = 217,
		BORDER_SINGLE_T_LEFT = 195,
		BORDER_SINGLE_T_RIGHT = 180,
		BORDER_SINGLE_T_TOP = 194,
		BORDER_SINGLE_T_BOTTOM = 193,
		BORDER_SINGLE_HORIZONTAL = 196,
		BORDER_SINGLE_VERTICAL = 179,
		BORDER_SINGLE_CROSS = 197,
		BORDER_DASHED_HORIZONTAL = 45,
		BORDER_DASHED_VERTICAL = 221,
		BORDER_DOTTED_HORIZONTAL = 250,
		BORDER_DOTTED_VERTICAL = 58
	};
}